import type { LineItem } from '../types/index';

export const DEFAULT_PRODUCTS: Omit<LineItem, 'id'>[] = [
  // Backend Lighting
  { scope: 'Backend Lighting', product: 'On/Off Lights', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'lighting.on-off' },
  { scope: 'Backend Lighting', product: 'Phasecut (Non-Dali Decorative)', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'lighting.phasecut' },
  { scope: 'Backend Lighting', product: 'Dali Dimmable', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'lighting.dali-dimmable' },
  { scope: 'Backend Lighting', product: 'Dali Tunable', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'lighting.dali-tunable' },
  { scope: 'Backend Lighting', product: 'Fan - On/Off', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'lighting.fan-on-off' },
  { scope: 'Backend Lighting', product: 'Fan - Speed Control', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'lighting.fan-speed' },
  // Temp / AC
  { scope: 'Temp / AC', product: 'AC', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'ac.ac' },
  // Front End
  { scope: 'Front End', product: '8 Button Keypad', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'frontend.keypad-8btn' },
  { scope: 'Front End', product: '4 Button Keypad', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'frontend.keypad-4btn' },
  { scope: 'Front End', product: 'Lira Push Button', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'frontend.lira-push' },
  { scope: 'Front End', product: 'Electrical Push Button', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'frontend.elec-push' },
  { scope: 'Front End', product: 'Remotes / Wireless Keypads', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'frontend.remotes' },
  { scope: 'Front End', product: 'iPad Docking Station', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'frontend.ipad-dock' },
  // IR
  { scope: 'IR', product: 'IR AV Controller', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'ir.av-controller' },
  // Motors
  { scope: 'Motors', product: 'Roman Blinds', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'motors.roman-blinds' },
  { scope: 'Motors', product: 'Roller Blinds', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'motors.roller-blinds' },
  { scope: 'Motors', product: 'American Curtains', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'motors.american-curtains' },
  { scope: 'Motors', product: 'Ripple Fold Curtains', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'motors.ripple-fold' },
  { scope: 'Motors', product: 'Bar Lift', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'motors.bar-lift' },
  // AV
  { scope: 'AV', product: 'Motorized Screen', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'av.motorized-screen' },
  { scope: 'AV', product: 'Fixed Screen', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'av.fixed-screen' },
  { scope: 'AV', product: 'Projector Lift', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'av.proj-lift' },
  { scope: 'AV', product: 'Motorized Drawer', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'av.motorized-drawer' },
  { scope: 'AV', product: 'TV Lift', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'av.tv-lift' },
  { scope: 'AV', product: 'AVR / Streamer', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'av.avr-streamer' },
  { scope: 'AV', product: 'Amplifier', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'av.amplifier' },
  { scope: 'AV', product: 'Projector', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'av.projector' },
  { scope: 'AV', product: 'TV', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'av.tv' },
  { scope: 'AV', product: 'Speakers', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'av.speakers' },
  { scope: 'AV', product: 'Woofer / Subwoofer', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'av.subwoofer' },
  // Networking
  { scope: 'Networking', product: 'Access Point', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'networking.access-point' },
  { scope: 'Networking', product: 'POE Switch', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'networking.poe-switch' },
  { scope: 'Networking', product: 'Non POE Switch', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'networking.non-poe-switch' },
  { scope: 'Networking', product: 'Dual WAN Firewall', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'networking.dual-wan-firewall' },
  // Integrated Security
  { scope: 'Integrated Security', product: 'IPBX', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'security.ipbx' },
  { scope: 'Integrated Security', product: 'CCTV', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'security.cctv' },
  { scope: 'Integrated Security', product: 'VDP', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'security.vdp' },
  { scope: 'Integrated Security', product: 'Readers', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'security.readers' },
  { scope: 'Integrated Security', product: 'Exit Button', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'security.exit-button' },
  { scope: 'Integrated Security', product: 'Locks', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'security.locks' },
  // Cables
  { scope: 'Cables', product: 'HDMI', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'cables.hdmi' },
  { scope: 'Cables', product: 'Speaker Cable', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'cables.speaker' },
  { scope: 'Cables', product: 'Woofer Cable', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'cables.woofer' },
  { scope: 'Cables', product: 'Optical', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'cables.optical' },
  { scope: 'Cables', product: 'Stereo', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'cables.stereo' },
  // Backend Infrastructure
  { scope: 'Backend Infrastructure', product: 'Networking Rack', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'backend.networking-rack' },
  { scope: 'Backend Infrastructure', product: 'Automation DB', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'backend.automation-db' },
  // General
  { scope: 'General', product: 'Alexa Integration', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'general.alexa' },
  { scope: 'General', product: 'Apple HomeKit', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'general.apple-homekit' },
  { scope: 'General', product: 'Crestron App', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'general.crestron-app' },
  { scope: 'General', product: 'Basalte Processor', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'general.basalte-processor' },
  // Sensors
  { scope: 'Sensors', product: 'Motion Sensors', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'sensors.motion' },
  // Processors
  { scope: 'Processors', product: 'Crestron', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'processors.crestron' },
  { scope: 'Processors', product: 'Basalte', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'processors.basalte' },
  { scope: 'Processors', product: 'Parriot', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'processors.parriot' },
  { scope: 'Processors', product: 'Cue', brand: '', modelNumber: '', specs: '', notes: '', roomAllocations: [], included: false, isCustom: false, canonicalKey: 'processors.cue' },
];

export const ALL_CANONICAL_KEYS: string[] = [
  'lighting.on-off',
  'lighting.phasecut',
  'lighting.dali-dimmable',
  'lighting.dali-tunable',
  'lighting.fan-on-off',
  'lighting.fan-speed',
  'ac.ac',
  'frontend.keypad-8btn',
  'frontend.keypad-4btn',
  'frontend.lira-push',
  'frontend.elec-push',
  'frontend.remotes',
  'frontend.ipad-dock',
  'ir.av-controller',
  'motors.roman-blinds',
  'motors.roller-blinds',
  'motors.american-curtains',
  'motors.ripple-fold',
  'motors.bar-lift',
  'av.motorized-screen',
  'av.fixed-screen',
  'av.proj-lift',
  'av.motorized-drawer',
  'av.tv-lift',
  'av.avr-streamer',
  'av.amplifier',
  'av.projector',
  'av.tv',
  'av.speakers',
  'av.subwoofer',
  'networking.access-point',
  'networking.poe-switch',
  'networking.non-poe-switch',
  'networking.dual-wan-firewall',
  'security.ipbx',
  'security.cctv',
  'security.vdp',
  'security.readers',
  'security.exit-button',
  'security.locks',
  'cables.hdmi',
  'cables.speaker',
  'cables.woofer',
  'cables.optical',
  'cables.stereo',
  'backend.networking-rack',
  'backend.automation-db',
  'general.alexa',
  'general.apple-homekit',
  'general.crestron-app',
  'general.basalte-processor',
  'sensors.motion',
  'processors.crestron',
  'processors.basalte',
  'processors.parriot',
  'processors.cue',
];

export const SCOPE_ORDER: string[] = [
  'Backend Lighting',
  'Temp / AC',
  'Front End',
  'IR',
  'Motors',
  'AV',
  'Networking',
  'Integrated Security',
  'Cables',
  'Backend Infrastructure',
  'General',
  'Sensors',
  'Processors',
];

export const SCOPE_COLORS: Record<string, string> = {
  'Backend Lighting': '#f59e0b',
  'Temp / AC': '#3b82f6',
  'Front End': '#8b5cf6',
  'IR': '#06b6d4',
  'Motors': '#f97316',
  'AV': '#6366f1',
  'Networking': '#0ea5e9',
  'Integrated Security': '#ef4444',
  'Cables': '#14b8a6',
  'Backend Infrastructure': '#d97706',
  'General': '#10b981',
  'Sensors': '#a855f7',
  'Processors': '#ec4899',
};

export function createDefaultLineItems(): LineItem[] {
  return DEFAULT_PRODUCTS.map((p, i) => ({
    ...p,
    id: `default_${i}_${Date.now()}_${Math.random().toString(36).slice(2)}`,
    roomAllocations: [],
  }));
}
